### PR TITLE
Project finished

### PR DESCRIPTION
**Pull request by tonyissa**
Instructions: Clone repo, change connection string, run project. Applying migrations not needed. 

Please let me know if you have any feedback :)

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@tonyissa Thanks for submitting, apologies for the delay ☹️

Are you able to build the project? I'm getting weird errors: 
image

**Comment by tonyissa** [comment]
Hi, thanks for the reply. I just deleted the repo and pulled it again and ran it with no build problems. Pic related. 

image

I really have no idea why it's throwing those errors though. Maybe trigger a rebuild and try again?

**Comment by TheCSharpAcademy** [comment]
@tonyissa Could you please send a video of the app showing the requirements being fulfilled? I still can't run it and don't have the time to figure it out 😄

**Comment by tonyissa** [comment]
> @tonyissa Could you please send a video of the app showing the requirements being fulfilled? I still can't run it and don't have the time to figure it out 😄

Sure. Here it is:

https://github.com/user-attachments/assets/45ddb6a2-d4ac-4cb6-8dda-015d50bab7d5

**Comment by TheCSharpAcademy** [comment]
@tonyissa Well done! Very nice that you included a modal for adding a new record! 👏🏻👏🏻

**Pull request closed without merging**
